import Gear from '#models/gear'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await Gear.createMany([
      {
        name: 'Blue Microphones Yeti, Micro USB pour Enregistrer, Streaming, Gaming, Podcast, PC & Mac, condensateur, avec Effets Blue VO!CE, Support ajustable, Plug and Play - Noir',
        description: 'ok',
        price: '112,53 €',
        gearCategory: 'usb-microphones',
        image: 'https://m.media-amazon.com/images/I/31qpzNSp0LL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B00N1YPXW2?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Sony Alpha 7 IV | Appareil photo hybride Expert plein format (33 mégapixels, mise au point AF en temps réel, rafale à 10 images/s, vidéo 4K 60p, écran orientable full tactile, nouveaux menus) Noir',
        description: 'ok',
        price: '2 609,90 €',
        gearCategory: 'cameras',
        image: 'https://m.media-amazon.com/images/I/311CpLHc0pL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B09JPCB3WR?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "Shure MV7 USB Podcast Microphone pour Le Podcasting, L'Enregistrement, Le Streaming et Les Jeux en Direct, Sortie Casque Intégrée, Micro Dynamique USB/XLR Entièrement Métallique - Noir",
        description: 'ok',
        price: '285,00 €',
        gearCategory: 'xlr-microphones',
        image: 'https://m.media-amazon.com/images/I/411zG0XzyJL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B08G7RG9ML?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Facecam - Webcam 1080p60 en vraie Full HD pour streaming, gaming et visio, capteur Sony, correction avancée de la lumière, commandes reflex, compatible OBS, Zoom, Teams et plus, pour PC/Mac',
        description: 'ok',
        price: '128,83 €',
        gearCategory: 'webcams',
        image: 'https://m.media-amazon.com/images/I/41f6+RR1zdL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0973DV11T?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'MAONO Microphone Dynamique XLR/USB PD400X',
        description: 'ok',
        price: '143,56 €',
        gearCategory: 'usb-microphones',
        image: 'https://m.media-amazon.com/images/I/41GHouzEZ7L._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0CDCMQC6N?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "Shure MV7 USB Podcast Microphone pour Le Podcasting, L'Enregistrement, Le Streaming et Les Jeux en Direct, Sortie Casque Intégrée, Micro Dynamique USB/XLR Entièrement Métallique - Noir",
        description: 'ok',
        price: '285,00 €',
        gearCategory: 'usb-microphones',
        image: 'https://m.media-amazon.com/images/I/411zG0XzyJL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B08G7RG9ML?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Logitech Brio Stream Webcam - Appels Vidéo HD Ultra 4K, Micro Anti-Bruit, Correction Automatique Lumière HD, Grand Angle, Compatible Microsoft Teams, Zoom, Google Meet PC / Mac - Noir',
        description: 'ok',
        price: '127,39 €',
        gearCategory: 'webcams',
        image: 'https://m.media-amazon.com/images/I/31raER4T4TL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0748NCPN5?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Logitech C920s HD Pro Webcam Streaming, Full HD 1080p/30ips, Appels Vidéos, Audio Clair, Correction Automatique de la Lumière, Volet de Protection, Skype, Zoom, Camera PC/Mac/Portable/Tablette/XBox',
        description: 'ok',
        price: '74,99 €',
        gearCategory: 'webcams',
        image: 'https://m.media-amazon.com/images/I/413c3lWANvL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07MM4V7NR?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Godox LED Light ES45 Kit pour E-Sports 2800K-6500K Barre de Montage avec Application et télécommande pour Youtube Game Live Photography Studio Lighting',
        description: 'ok',
        price: '119,00 €',
        gearCategory: 'lights',
        image: 'https://m.media-amazon.com/images/I/31YsD2euaxL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B08ZBCHDJH?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Relota Bras Micro Réglable, Support de Microphone Noir avec Filtre Anti-Pop, Pince à Micro, 5 Attaches de Câble, Anti-choc, Perche Micro Suspension pour Studio, Diffusion, Enregistrement, Gaming',
        description: 'ok',
        price: '17,99 €',
        gearCategory: 'microphone-stands',
        image: 'https://m.media-amazon.com/images/I/41ejJG6EQjL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0BW3ZD8N9?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "RØDE NT-USB+ Microphone USB professionnel pour l'enregistrement d'un audio exceptionnel directement sur un ordinateur ou un appareil mobile",
        description: 'ok',
        price: '177,00 €',
        gearCategory: 'usb-microphones',
        image: 'https://m.media-amazon.com/images/I/41u1qjaYDoL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B00MMKQOEM?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Canon EOS M50 Mark II + EF-M 15-45mm is STM (obsolete ou périmé)',
        description: 'ok',
        price: '749,00 €',
        gearCategory: 'cameras',
        image: 'https://m.media-amazon.com/images/I/41oDaDws-OL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B08KSKV35C?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Ring Light - Éclairage premium 2 500 lumens avec pince pour bureau et rotule pour streaming, TikTok, Instagram et télétravail, avec température et luminosité réglables sur Mac, PC, iOS, Android',
        description: 'ok',
        price: '187,54 €',
        gearCategory: 'lights',
        image: 'https://m.media-amazon.com/images/I/31+-IPorGvL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B08GMDQ87T?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "Shure MV7X XLR Podcast Microphone pour le Podcasting, l'enregistrement, la Diffusion en Direct et les Jeux, Sortie Casque Intégrée, XLR, Technologie d'isolation de la Voix - Noir",
        description: 'ok',
        price: '165,00 €',
        gearCategory: 'xlr-microphones',
        image: 'https://m.media-amazon.com/images/I/41euWqyRE7L._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B09BZZCGC8?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "RØDE NT1 Signature Series Microphone à condensateur, Filtre Anti-Pop et câble XLR pour la Production Musicale et l'enregistrement Vocal",
        description: 'ok',
        price: '163,00 €',
        gearCategory: 'xlr-microphones',
        image: 'https://m.media-amazon.com/images/I/41n-E8tvomL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0CKVD62NX?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "Sony Alpha 6400|Appareil Photo Numérique Hybride APS-C en kit avec l'Objectif Zoom E 16-50mm f/3.5-5.6 PZ OSS (24,2 MP, AF en 0.02s, Suivi des Yeux, 4K HLG, Ecran Selfie Vlogging)(ILCE6400, A6400)",
        description: 'ok',
        price: '991,10 €',
        gearCategory: 'cameras',
        image: 'https://m.media-amazon.com/images/I/41PYMAcf-WL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07MWDP1VD?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'AMANKA Cartes de Capture Audio vidéo, 1080p Adaptateur HDMI vers USB, Carte Portable Plug & Play Capture, pour Streaming vidéo en Direct Enregistrement vidéo ou Diffusion en Direct',
        description: 'ok',
        price: '9,99 €',
        gearCategory: 'capture-cards',
        image: 'https://m.media-amazon.com/images/I/41E1KOi3SXL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B08CZJFV7S?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'AKG K702 Casque Supra-Auriculaire de Référence Premium Studio à Dos Ouvert',
        description: 'ok',
        price: '139,00 €',
        gearCategory: 'headphones',
        image: 'https://m.media-amazon.com/images/I/41VgG8D-oGL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B001RCD2DW?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Razer Seiren Mini - Microphone à condensateur USB pour Le Streaming (Compact avec directivité supercardioïde, Support inclinable, Amortisseur de Chocs intégré) Noir',
        description: 'ok',
        price: '53,83 €',
        gearCategory: 'usb-microphones',
        image: 'https://m.media-amazon.com/images/I/31RbJJ0mGjL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B00PADOYP4?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Logitech for Creators StreamCam, webcam pour streaming YouTube et Twitch, full HD 1080p 60Fps, connexion USB-C, détection des visages par IA, mise au point automatique, vidéo verticale - Noir',
        description: 'ok',
        price: '119,99 €',
        gearCategory: 'webcams',
        image: 'https://m.media-amazon.com/images/I/41nO6N1HloL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07W4DHNBF?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "TARION Support de Bureau pour Appareil Photo trépied aérien Bras articulé Flexible à 360° avec vis 3/8' et vis 3/8' à 1/4' Reflex numériques Projecteur Ring Light TKB01",
        description: 'ok',
        price: '39,99 €',
        gearCategory: 'camera-stands',
        image: 'https://m.media-amazon.com/images/I/31oJrPAWzsL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0C1GJWJZ7?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Focusrite Interface audio USB Scarlett Solo de 3e génération, pour les guitaristes, chanteurs(ses) et réalisateurs(trices), accompagnée de tous les logiciels dont vous avez besoin pour enregistrer',
        description: 'ok',
        price: '109,99 €',
        gearCategory: 'audio-interfaces',
        image: 'https://m.media-amazon.com/images/I/31Ty6bmUmVL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07QR6Z1JB?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'TARION caméra Bras articulé Support Pince de Table trépied trépied de Table réglable avec Adaptateur à vis 3/8" à 1/4" (L)',
        description: 'ok',
        price: '53,47 €',
        gearCategory: 'camera-stands',
        image: 'https://m.media-amazon.com/images/I/41tdoEeINvL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B09MQ9GPCZ?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'AKG K72 Casque de monitoring fermé haute performance',
        description: 'ok',
        price: '47,00 €',
        gearCategory: 'headphones',
        image: 'https://m.media-amazon.com/images/I/31byaLYGEtL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B01AYSNHVQ?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Sony Alpha ZV-E10 | Appareil photo vidéo hybride APS-C Vlog avec optique zoom motorisée 16-50mm f/3.5-5.6 (écran orientable pour le vlogging, vidéo 4K, autofocus en temps réel sur les yeux) Gris',
        description: 'ok',
        price: '829,00 €',
        gearCategory: 'cameras',
        image: 'https://m.media-amazon.com/images/I/51rkIm6q6AL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B098M236VR?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato 4K60 Pro MK.2, carte d’acquisition interne, streaming et enregistrement en 4K60 HDR10 à ultra faible latence sur PS5, PS4 Pro, Xbox Series X/S, Xbox One X dans OBS, Twitch, YouTube, pour PC',
        description: 'ok',
        price: '230,67 €',
        gearCategory: 'capture-cards',
        image: 'https://m.media-amazon.com/images/I/3154sKTlXxL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07VWXCXM7?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Master Mount L, pince pour bureau haut de gamme avec perche télescopique jusqu’à 125 cm et filetage 1/4" pour fixer des lumières, caméras et micros, idéale pour streaming, visio et studios',
        description: 'ok',
        price: '68,81 €',
        gearCategory: 'camera-stands',
        image: 'https://m.media-amazon.com/images/I/21NZCDJ25gL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07X49967V?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Wave Mic Arm LP - Perche de micro haut de gamme compacte avec passe-câbles, pince pour bureau, fixation polyvalente, entièrement réglable, idéale pour podcasts, streaming, jeux, télétravail',
        description: 'ok',
        price: '99,99 €',
        gearCategory: 'microphone-stands',
        image: 'https://m.media-amazon.com/images/I/31uBXDHIaUL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B097376LKF?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'OBSBOT Tiny 2 - PTZ 4K Webcam avec Suivi AI, Commande Vocale, Commande Gestuelle, Microphones Réducteurs de Bruit, Autofocus, USB3.0, Modes Multiples, Webcam pour PC, Conférence, Streaming, Zoom',
        description: 'ok',
        price: '369,00 €',
        gearCategory: 'webcams',
        image: 'https://m.media-amazon.com/images/I/31F5gYnx3lL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0C3B6ZR1V?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Blue Microphones Compass, Bras Micro Blue Yeti, Type Tubulaire, Bras Micro Articulé, Ressorts Internes, Pince Bureau, Gestion de Câbles Intégrée, Enregistrement, Gaming, Streaming, Podcast - Noir',
        description: 'ok',
        price: '89,00 €',
        gearCategory: 'microphone-stands',
        image: 'https://m.media-amazon.com/images/I/21IXnFxRE4L._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B078MLBGRM?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Bras de Microphone TONOR, Bras de Micro à Profil Bas de Première Qualité pour Streaming, Recording, Entièrement Ajustable 360° Rotatif 90° Pliable pour HyperX Blue Yeti Shure Rode Razer T20LP',
        description: 'ok',
        price: '34,99 €',
        gearCategory: 'microphone-stands',
        image: 'https://m.media-amazon.com/images/I/31CMWEaErZL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0CFKHCQ8W?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'AUNA Pro MIC-900 - Microphone Studio, Micro, Capsule de 16 mm, Caractéristique cardioide, Étoile et charnière 57/8" incluses, Châssis en métal, USB Type B, USB - Noir',
        description: 'ok',
        price: '49,99 €',
        gearCategory: 'usb-microphones',
        image: 'https://m.media-amazon.com/images/I/41c3WkORIAL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B00AE4T0Q2?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato HD60 S+, carte d’acquisition externe, streaming et enregistrement en 1080p60 ou 4K60 HDR10 à ultra faible latence sur PS5, PS4/Pro, Xbox Series X/S, Xbox One X/S dans OBS, compatible PC/Mac',
        description: 'ok',
        price: '307,07 €',
        gearCategory: 'capture-cards',
        image: 'https://m.media-amazon.com/images/I/31hOxOwjvjL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07XB6VNLJ?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'beyerdynamic DT 770 PRO 80 Ohm en noir. Casque de studio supra-auriculaire. Conception fermée, câblée pour un enregistrement et une surveillance professionnels',
        description: 'ok',
        price: '137,00 €',
        gearCategory: 'headphones',
        image: 'https://m.media-amazon.com/images/I/31dczklm2aL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0016MNAAI?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Solid Arm, perche de support avec pince à revêtement de protection pour fixer et régler facilement lumières, caméras et micros, idéale pour le streaming, la visioconférence et les studios',
        description: 'ok',
        price: '21,90 €',
        gearCategory: 'camera-stands',
        image: 'https://m.media-amazon.com/images/I/31Jl0bwTQ9L._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B08GMBRZQH?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'FIFINE USB/XLR Streaming Micro Dynamique pour PC, RGB Cardioïde Microphone pour Gaming, Podcasting, Broadcasting, Enregistrement Vocal, pour PS4/5 Mac PC Mixer Cartes Son',
        description: 'ok',
        price: '79,99 €',
        gearCategory: 'usb-microphones',
        image: 'https://m.media-amazon.com/images/I/41XiUtCfwVL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0C4KVBBZM?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "RØDE PodMic Microphone dynamique de qualité Broadcast avec support oscillant intégré pour les podcasts, le streaming, le jeu, et l'enregistrement vocal",
        description: 'ok',
        price: '98,00 €',
        gearCategory: 'xlr-microphones',
        image: 'https://m.media-amazon.com/images/I/41onC+bLofL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07MSCRCVK?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Panasonic Lumix GH5M2 | Appareil photo Hybride Expert (Capteur 4/3 20.3MP, Double stab., Écran orient. tact., AF DFD 225 Zones, C4K 60p/4:2:2 10bit, Live Stream., Tropicalisé) Noir – Version Française',
        description: 'ok',
        price: '1 099,00 €',
        gearCategory: 'cameras',
        image: 'https://m.media-amazon.com/images/I/41xFAaSVcIL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B096MTVJQL?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'RØDE RØDECaster Pro II Solution de production tout-en-un pour le podcasting, le streaming, la production musicale et la création de contenu',
        description: 'ok',
        price: '699,00 €',
        gearCategory: 'audio-interfaces',
        image: 'https://m.media-amazon.com/images/I/51VJGEJzlXL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0B17V8NGX?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Mini Mount – Support de bureau polyvalent extensible à 64 cm, entièrement réglable, support de téléphone à sabot, emplacement pour appareil et filetage 1/4" pour caméra, éclairage, micro, etc.',
        description: 'ok',
        price: '59,99 €',
        gearCategory: 'camera-stands',
        image: 'https://m.media-amazon.com/images/I/31InTmT6UtL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0BBNZ38JZ?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'TC Helicon USB Plateforme de Diffusion en Ligne Révolutionnaire Goxlr avec Mélangeur 4 Canaux, Faders Motorisés, Table de son et Effets Vocaux ,Compatible PC Uniquement',
        description: 'ok',
        price: '329,00 €',
        gearCategory: 'audio-interfaces',
        image: 'https://m.media-amazon.com/images/I/414ZM+H4a4L._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07JKNG4NV?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "Interface audio USB Focusrite Scarlett 2i2 de 3e génération pour l'enregistrement des prises de son haute fidélité, de qualité studio, et tous les logiciels dont vous avez besoin pour enregistrer",
        description: 'ok',
        price: '120,00 €',
        gearCategory: 'audio-interfaces',
        image: 'https://m.media-amazon.com/images/I/31nAb3Cx4jL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07QR73T66?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Panasonic-Lumix G7KEC K-Cámara numérique interchangeable avec objectif de 14-42 mm (16 mégapixels écran de 3" enregistrement vidéo 4 K,) WiFi Noir',
        description: 'ok',
        price: '514,51 €',
        gearCategory: 'cameras',
        image: 'https://m.media-amazon.com/images/I/31nBayOR3aL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B00ZXI7UFC?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'beyerdynamic Dt 990 Pro - Casque audio supra-auriculaire pour moniteurs de studio - Construction stéréo à dos ouvert, filaire, 80 Ohm, noir (édition limitée)',
        description: 'ok',
        price: '149,00 €',
        gearCategory: 'headphones',
        image: 'https://m.media-amazon.com/images/I/41pQJyOzbDL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07KFLX8HV?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Shure SM7B Microphone Dynamique Cardioïde, Son Doux et Chaleureux pour Le Broadcast, Le Podcast ou L’Enregistrement',
        description: 'ok',
        price: '385,00 €',
        gearCategory: 'xlr-microphones',
        image: 'https://m.media-amazon.com/images/I/412JztpzjoS._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0002E4Z8M?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "Elgato Wave:3 - Micro à condensateur USB de qualité studio pour streaming, podcasts, gaming et télétravail, logiciel de mixage gratuit, plug-ins d'effets, anti-distorsion, plug & play sur Mac et PC",
        description: 'ok',
        price: '154,99 €',
        gearCategory: 'usb-microphones',
        image: 'https://m.media-amazon.com/images/I/41mjwnzHOJL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B088HHWC47?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Wave DX - Micro XLR dynamique cardioïde, suppression de bruit, optimisation des voix pour podcast, streaming et diffusion, booster de signal non requis, compatible toutes interfaces, Mac et PC',
        description: 'ok',
        price: '119,99 €',
        gearCategory: 'xlr-microphones',
        image: 'https://m.media-amazon.com/images/I/41Q+cbbSDTL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0B8GRCXB6?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'BILIONE Support de microphone de bureau amélioré, support de micro réglable avec filtre anti-pop, support antichoc, clip de microphone, adaptateur à vis en métal de 1,5 cm à 9,5 mm',
        description: 'ok',
        price: '29,88 €',
        gearCategory: 'microphone-stands',
        image: 'https://m.media-amazon.com/images/I/41b4kb6VjrL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B08TBJPL56?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Insta360 Link - Webcam PTZ 4K avec capteur 1/2", suivi de l\'IA, contrôle gestuel, HDR, microphones avec réduction du bruit, modes spéciaux, pour ordinateur portable, caméra vidéo pour vidéoconférence,',
        description: 'ok',
        price: '309,99 €',
        gearCategory: 'webcams',
        image: 'https://m.media-amazon.com/images/I/31zKY06+GoL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0B826KS4B?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Flex Arm L, perche articulée haut de gamme en 4 parties pour fixer et régler facilement lumières, caméras et micros, idéale pour streaming, visio et studios, nécessite Multi Mount Essential',
        description: 'ok',
        price: '49,99 €',
        gearCategory: 'camera-stands',
        image: 'https://m.media-amazon.com/images/I/31aFJkeBeIL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07X49967Y?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Cam Link 4K, carte d’acquisition externe pour caméra, streaming et enregistrement sur reflex ou caméscope en 1080p60/4K30 pour visioconférence, télétravail ou jeux, sur OBS, Zoom, Teams, PC/Mac',
        description: 'ok',
        price: '115,05 €',
        gearCategory: 'capture-cards',
        image: 'https://m.media-amazon.com/images/I/31eW9XxyowL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07K3FN5MR?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Universal Audio Volt 176 Interface audio USB, pour enregistrer, podcaster et streamer avec des logiciels audio essentiels',
        description: 'ok',
        price: '185,00 €',
        gearCategory: 'audio-interfaces',
        image: 'https://m.media-amazon.com/images/I/41OjMNTMPcL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B09J1W9NHV?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Panasonic Lumix GH6 | Appareil photo vidéo Hybride Expert (Capt 4/3 25MP, Vidéo illimitée, 5.7K 60p / C4K 422 10bit, Apple ProRes, Slow Motion 4K 120p, Tropicalisé) – Version Française',
        description: 'ok',
        price: '1 799,00 €',
        gearCategory: 'cameras',
        image: 'https://m.media-amazon.com/images/I/41d7fni89lL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B09TFLPFKR?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'AVerMedia Carte de Capture HDMI 2.1 pour Streaming et Jeux, Prise en Charge VRR et Carte de Capture HDR 4K pour Xbox Series x/s, PS5, Xbox One, PS4, Switch-GC553G2 Live Gamer Ultra 2.1',
        description: 'ok',
        price: '299,99 €',
        gearCategory: 'capture-cards',
        image: 'https://m.media-amazon.com/images/I/41MYPPpmEaL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0CGD86HNB?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Sony Alpha 7 III | Appareil Photo Numérique Hybride Plein Format ( 24,2 MP, AF en 0.02s, Suivi des Yeux, stabilisation interne 5 axes, 4K HLG, Batterie Haute Capacité) (ILCE7M3, A7M3)',
        description: 'ok',
        price: '1 750,00 €',
        gearCategory: 'cameras',
        image: 'https://m.media-amazon.com/images/I/41CgxdelDNL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07B4L1PQ8?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: "SmallRig Selection Support de Table pour Appareil Photo Montage sur Bureau avec Rotule 1/4\", Support d'Éclairage Réglable de 13'' à 35,4''(33cm-90cm), Pince de Table en C - 3488",
        description: 'ok',
        price: '32,90 €',
        gearCategory: 'camera-stands',
        image: 'https://m.media-amazon.com/images/I/31Zy+lzlm8L._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B09FLPGMNJ?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Logitech Litra Glow Premium, Light LED Streaming avec TrueSoft - Lumière Ordinateur pour vidéoconférences, Zoom, Ajustable & App Contrôle pour PC/Mac - Graphite',
        description: 'ok',
        price: '69,99 €',
        gearCategory: 'lights',
        image: 'https://m.media-amazon.com/images/I/21ZCgx+xmkL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B07W4DHXC8?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Bird Woodbrass UM1 Noir - Microphone USB Cardioïde à Condensateur PC et Mac pour Broadcast et Enregistrement Streaming, Podcasting, Conférence, Home Studio Mao, Voix Off',
        description: 'ok',
        price: '49,00 €',
        gearCategory: 'usb-microphones',
        image: 'https://m.media-amazon.com/images/I/31FFPsFI31L._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B00EQ077RE?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Wave XLR - Console et préampli 75 dB pour micro XLR vers USB-C, interface à alimentation fantôme 48 V, Mute tactile, logiciel de mixage pour streaming, enregistrement, podcasts sur Mac et PC',
        description: 'ok',
        price: '159,99 €',
        gearCategory: 'audio-interfaces',
        image: 'https://m.media-amazon.com/images/I/31z6ruz3DHS._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B09738CKKX?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Facecam Pro - Webcam Ultra HD en vraie 4K60 pour streaming, gaming et visio, capteur Sony, correction de lumière avancée, commandes reflex, grand-angle, compatible OBS, Teams, Zoom, pour PC/Mac',
        description: 'ok',
        price: '349,96 €',
        gearCategory: 'webcams',
        image: 'https://m.media-amazon.com/images/I/41fLjPsHwJL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0BJL7Q3SR?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'RØDE Streamer X Interface audio intégrée professionnelle et carte de capture vidéo 4K avec connectivité XLR, HDMI et TRRS pour streaming, jeu et création de contenu',
        description: 'ok',
        price: '331,07 €',
        gearCategory: 'audio-interfaces',
        image: 'https://m.media-amazon.com/images/I/41u7Kk4P5GL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0BQM2CL1W?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Elgato Key Light Air - Éclairage de bureau pro 1 400 lumens pour streaming, diffusion, télétravail et visioconférence, avec température et luminosité réglables sur Mac, PC, iOS et Android',
        description: 'ok',
        price: '135,48 €',
        gearCategory: 'lights',
        image: 'https://m.media-amazon.com/images/I/218zsIOCJpL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B082QHRZFW?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'Godox SL60II-D SL-60W Upgraded CRI 96+,TLCI 97+ LED Video Light White Daylight Continuous Light 5600±200K 70W Bowens Mount New APP Control with 8-FX Effects + RC-A6 Remote Control',
        description: 'ok',
        price: '126,00 €',
        gearCategory: 'lights',
        image: 'https://m.media-amazon.com/images/I/41HqXJhx79L._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B0BW5YSY6K?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
      {
        name: 'RØDE PSA1 Bras de studio professionnel',
        description: 'ok',
        price: '89,00 €',
        gearCategory: 'camera-stands',
        image: 'https://m.media-amazon.com/images/I/31mx6aaLfIL._SL500_.jpg',
        link: 'https://www.amazon.fr/dp/B001D7UYBO?tag=streamertoo09-21&linkCode=osi&th=1&psc=1',
      },
    ])
  }
}
